//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from mdx.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ImdxListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class mdxBaseListener : ImdxListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.mdx_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMdx_statement([NotNull] mdxParser.Mdx_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.mdx_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMdx_statement([NotNull] mdxParser.Mdx_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.select_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelect_statement([NotNull] mdxParser.Select_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.select_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelect_statement([NotNull] mdxParser.Select_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.formula_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormula_specification([NotNull] mdxParser.Formula_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.formula_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormula_specification([NotNull] mdxParser.Formula_specificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.single_formula_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_formula_specification([NotNull] mdxParser.Single_formula_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.single_formula_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_formula_specification([NotNull] mdxParser.Single_formula_specificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.set_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_specification([NotNull] mdxParser.Set_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.set_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_specification([NotNull] mdxParser.Set_specificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_specification([NotNull] mdxParser.Member_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_specification([NotNull] mdxParser.Member_specificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.axis_specification_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxis_specification_list([NotNull] mdxParser.Axis_specification_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.axis_specification_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxis_specification_list([NotNull] mdxParser.Axis_specification_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_property_def_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_property_def_list([NotNull] mdxParser.Member_property_def_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_property_def_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_property_def_list([NotNull] mdxParser.Member_property_def_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_name([NotNull] mdxParser.Member_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_name([NotNull] mdxParser.Member_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_property_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMember_property_definition([NotNull] mdxParser.Member_property_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_property_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMember_property_definition([NotNull] mdxParser.Member_property_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.set_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_name([NotNull] mdxParser.Set_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.set_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_name([NotNull] mdxParser.Set_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.compound_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_id([NotNull] mdxParser.Compound_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.compound_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_id([NotNull] mdxParser.Compound_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.axis_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxis_specification([NotNull] mdxParser.Axis_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.axis_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxis_specification([NotNull] mdxParser.Axis_specificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.axis_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxis_name([NotNull] mdxParser.Axis_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.axis_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxis_name([NotNull] mdxParser.Axis_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.dim_props"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDim_props([NotNull] mdxParser.Dim_propsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.dim_props"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDim_props([NotNull] mdxParser.Dim_propsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.property_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty_list([NotNull] mdxParser.Property_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.property_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty_list([NotNull] mdxParser.Property_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProperty([NotNull] mdxParser.PropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProperty([NotNull] mdxParser.PropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cube_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCube_specification([NotNull] mdxParser.Cube_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cube_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCube_specification([NotNull] mdxParser.Cube_specificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cube_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCube_name([NotNull] mdxParser.Cube_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cube_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCube_name([NotNull] mdxParser.Cube_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.slicer_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSlicer_specification([NotNull] mdxParser.Slicer_specificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.slicer_specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSlicer_specification([NotNull] mdxParser.Slicer_specificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cell_props"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCell_props([NotNull] mdxParser.Cell_propsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cell_props"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCell_props([NotNull] mdxParser.Cell_propsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cell_property_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCell_property_list([NotNull] mdxParser.Cell_property_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cell_property_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCell_property_list([NotNull] mdxParser.Cell_property_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cell_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCell_property([NotNull] mdxParser.Cell_propertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cell_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCell_property([NotNull] mdxParser.Cell_propertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.mandatory_cell_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMandatory_cell_property([NotNull] mdxParser.Mandatory_cell_propertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.mandatory_cell_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMandatory_cell_property([NotNull] mdxParser.Mandatory_cell_propertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.provider_specific_cell_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProvider_specific_cell_property([NotNull] mdxParser.Provider_specific_cell_propertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.provider_specific_cell_property"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProvider_specific_cell_property([NotNull] mdxParser.Provider_specific_cell_propertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] mdxParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] mdxParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_expression([NotNull] mdxParser.Value_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_expression([NotNull] mdxParser.Value_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_xor_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_xor_expression([NotNull] mdxParser.Value_xor_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_xor_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_xor_expression([NotNull] mdxParser.Value_xor_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_or_expression([NotNull] mdxParser.Value_or_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_or_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_or_expression([NotNull] mdxParser.Value_or_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term5"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm5([NotNull] mdxParser.Term5Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term5"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm5([NotNull] mdxParser.Term5Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm4([NotNull] mdxParser.Term4Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term4"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm4([NotNull] mdxParser.Term4Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm3([NotNull] mdxParser.Term3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm3([NotNull] mdxParser.Term3Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm2([NotNull] mdxParser.Term2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm2([NotNull] mdxParser.Term2Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] mdxParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] mdxParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] mdxParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] mdxParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] mdxParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] mdxParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_expression_primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_expression_primary([NotNull] mdxParser.Value_expression_primaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_expression_primary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_expression_primary([NotNull] mdxParser.Value_expression_primaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_expression_primary0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_expression_primary0([NotNull] mdxParser.Value_expression_primary0Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_expression_primary0"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_expression_primary0([NotNull] mdxParser.Value_expression_primary0Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.exp_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp_list([NotNull] mdxParser.Exp_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.exp_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp_list([NotNull] mdxParser.Exp_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.case_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCase_expression([NotNull] mdxParser.Case_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.case_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCase_expression([NotNull] mdxParser.Case_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.when_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhen_list([NotNull] mdxParser.When_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.when_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhen_list([NotNull] mdxParser.When_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.when_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhen_clause([NotNull] mdxParser.When_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.when_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhen_clause([NotNull] mdxParser.When_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.comp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_op([NotNull] mdxParser.Comp_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.comp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_op([NotNull] mdxParser.Comp_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] mdxParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] mdxParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.unquoted_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnquoted_identifier([NotNull] mdxParser.Unquoted_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.unquoted_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnquoted_identifier([NotNull] mdxParser.Unquoted_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.amp_quoted_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAmp_quoted_identifier([NotNull] mdxParser.Amp_quoted_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.amp_quoted_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAmp_quoted_identifier([NotNull] mdxParser.Amp_quoted_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.quoted_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuoted_identifier([NotNull] mdxParser.Quoted_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.quoted_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuoted_identifier([NotNull] mdxParser.Quoted_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] mdxParser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] mdxParser.KeywordContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
