//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from mdx.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="mdxParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ImdxListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.mdx_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMdx_statement([NotNull] mdxParser.Mdx_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.mdx_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMdx_statement([NotNull] mdxParser.Mdx_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_statement([NotNull] mdxParser.Select_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_statement([NotNull] mdxParser.Select_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.formula_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormula_specification([NotNull] mdxParser.Formula_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.formula_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormula_specification([NotNull] mdxParser.Formula_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.single_formula_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_formula_specification([NotNull] mdxParser.Single_formula_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.single_formula_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_formula_specification([NotNull] mdxParser.Single_formula_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.set_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_specification([NotNull] mdxParser.Set_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.set_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_specification([NotNull] mdxParser.Set_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_specification([NotNull] mdxParser.Member_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_specification([NotNull] mdxParser.Member_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.axis_specification_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAxis_specification_list([NotNull] mdxParser.Axis_specification_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.axis_specification_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAxis_specification_list([NotNull] mdxParser.Axis_specification_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_property_def_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_property_def_list([NotNull] mdxParser.Member_property_def_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_property_def_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_property_def_list([NotNull] mdxParser.Member_property_def_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_name([NotNull] mdxParser.Member_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_name([NotNull] mdxParser.Member_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.member_property_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMember_property_definition([NotNull] mdxParser.Member_property_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.member_property_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMember_property_definition([NotNull] mdxParser.Member_property_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.set_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_name([NotNull] mdxParser.Set_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.set_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_name([NotNull] mdxParser.Set_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.compound_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_id([NotNull] mdxParser.Compound_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.compound_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_id([NotNull] mdxParser.Compound_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.axis_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAxis_specification([NotNull] mdxParser.Axis_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.axis_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAxis_specification([NotNull] mdxParser.Axis_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.axis_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAxis_name([NotNull] mdxParser.Axis_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.axis_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAxis_name([NotNull] mdxParser.Axis_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.dim_props"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDim_props([NotNull] mdxParser.Dim_propsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.dim_props"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDim_props([NotNull] mdxParser.Dim_propsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.property_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty_list([NotNull] mdxParser.Property_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.property_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty_list([NotNull] mdxParser.Property_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProperty([NotNull] mdxParser.PropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProperty([NotNull] mdxParser.PropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cube_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCube_specification([NotNull] mdxParser.Cube_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cube_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCube_specification([NotNull] mdxParser.Cube_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cube_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCube_name([NotNull] mdxParser.Cube_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cube_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCube_name([NotNull] mdxParser.Cube_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.slicer_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSlicer_specification([NotNull] mdxParser.Slicer_specificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.slicer_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSlicer_specification([NotNull] mdxParser.Slicer_specificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cell_props"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCell_props([NotNull] mdxParser.Cell_propsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cell_props"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCell_props([NotNull] mdxParser.Cell_propsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cell_property_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCell_property_list([NotNull] mdxParser.Cell_property_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cell_property_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCell_property_list([NotNull] mdxParser.Cell_property_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCell_property([NotNull] mdxParser.Cell_propertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCell_property([NotNull] mdxParser.Cell_propertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.mandatory_cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMandatory_cell_property([NotNull] mdxParser.Mandatory_cell_propertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.mandatory_cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMandatory_cell_property([NotNull] mdxParser.Mandatory_cell_propertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.provider_specific_cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProvider_specific_cell_property([NotNull] mdxParser.Provider_specific_cell_propertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.provider_specific_cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProvider_specific_cell_property([NotNull] mdxParser.Provider_specific_cell_propertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] mdxParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] mdxParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_expression([NotNull] mdxParser.Value_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_expression([NotNull] mdxParser.Value_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_xor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_xor_expression([NotNull] mdxParser.Value_xor_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_xor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_xor_expression([NotNull] mdxParser.Value_xor_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_or_expression([NotNull] mdxParser.Value_or_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_or_expression([NotNull] mdxParser.Value_or_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm5([NotNull] mdxParser.Term5Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm5([NotNull] mdxParser.Term5Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm4([NotNull] mdxParser.Term4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm4([NotNull] mdxParser.Term4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm3([NotNull] mdxParser.Term3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm3([NotNull] mdxParser.Term3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm2([NotNull] mdxParser.Term2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm2([NotNull] mdxParser.Term2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] mdxParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] mdxParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] mdxParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] mdxParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] mdxParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] mdxParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_expression_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_expression_primary([NotNull] mdxParser.Value_expression_primaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_expression_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_expression_primary([NotNull] mdxParser.Value_expression_primaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.value_expression_primary0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_expression_primary0([NotNull] mdxParser.Value_expression_primary0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.value_expression_primary0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_expression_primary0([NotNull] mdxParser.Value_expression_primary0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.exp_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp_list([NotNull] mdxParser.Exp_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.exp_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp_list([NotNull] mdxParser.Exp_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.case_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCase_expression([NotNull] mdxParser.Case_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.case_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCase_expression([NotNull] mdxParser.Case_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.when_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhen_list([NotNull] mdxParser.When_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.when_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhen_list([NotNull] mdxParser.When_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.when_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhen_clause([NotNull] mdxParser.When_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.when_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhen_clause([NotNull] mdxParser.When_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.comp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComp_op([NotNull] mdxParser.Comp_opContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.comp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComp_op([NotNull] mdxParser.Comp_opContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] mdxParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] mdxParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.unquoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnquoted_identifier([NotNull] mdxParser.Unquoted_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.unquoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnquoted_identifier([NotNull] mdxParser.Unquoted_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.amp_quoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmp_quoted_identifier([NotNull] mdxParser.Amp_quoted_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.amp_quoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmp_quoted_identifier([NotNull] mdxParser.Amp_quoted_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.quoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuoted_identifier([NotNull] mdxParser.Quoted_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.quoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuoted_identifier([NotNull] mdxParser.Quoted_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="mdxParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKeyword([NotNull] mdxParser.KeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="mdxParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKeyword([NotNull] mdxParser.KeywordContext context);
}
