//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from mdx.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="mdxParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface ImdxVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.mdx_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMdx_statement([NotNull] mdxParser.Mdx_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.select_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_statement([NotNull] mdxParser.Select_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.formula_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula_specification([NotNull] mdxParser.Formula_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.single_formula_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_formula_specification([NotNull] mdxParser.Single_formula_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.set_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_specification([NotNull] mdxParser.Set_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.member_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_specification([NotNull] mdxParser.Member_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.axis_specification_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_specification_list([NotNull] mdxParser.Axis_specification_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.member_property_def_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_property_def_list([NotNull] mdxParser.Member_property_def_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.member_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_name([NotNull] mdxParser.Member_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.member_property_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_property_definition([NotNull] mdxParser.Member_property_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.set_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_name([NotNull] mdxParser.Set_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.compound_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_id([NotNull] mdxParser.Compound_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.axis_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_specification([NotNull] mdxParser.Axis_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.axis_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_name([NotNull] mdxParser.Axis_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.dim_props"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDim_props([NotNull] mdxParser.Dim_propsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.property_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty_list([NotNull] mdxParser.Property_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProperty([NotNull] mdxParser.PropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.cube_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCube_specification([NotNull] mdxParser.Cube_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.cube_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCube_name([NotNull] mdxParser.Cube_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.slicer_specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlicer_specification([NotNull] mdxParser.Slicer_specificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.cell_props"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCell_props([NotNull] mdxParser.Cell_propsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.cell_property_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCell_property_list([NotNull] mdxParser.Cell_property_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCell_property([NotNull] mdxParser.Cell_propertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.mandatory_cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMandatory_cell_property([NotNull] mdxParser.Mandatory_cell_propertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.provider_specific_cell_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProvider_specific_cell_property([NotNull] mdxParser.Provider_specific_cell_propertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] mdxParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.value_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_expression([NotNull] mdxParser.Value_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.value_xor_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_xor_expression([NotNull] mdxParser.Value_xor_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.value_or_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_or_expression([NotNull] mdxParser.Value_or_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.term5"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm5([NotNull] mdxParser.Term5Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.term4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm4([NotNull] mdxParser.Term4Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.term3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm3([NotNull] mdxParser.Term3Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.term2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm2([NotNull] mdxParser.Term2Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] mdxParser.TermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] mdxParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] mdxParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.value_expression_primary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_expression_primary([NotNull] mdxParser.Value_expression_primaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.value_expression_primary0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_expression_primary0([NotNull] mdxParser.Value_expression_primary0Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.exp_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp_list([NotNull] mdxParser.Exp_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.case_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_expression([NotNull] mdxParser.Case_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.when_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhen_list([NotNull] mdxParser.When_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.when_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhen_clause([NotNull] mdxParser.When_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.comp_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComp_op([NotNull] mdxParser.Comp_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] mdxParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.unquoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnquoted_identifier([NotNull] mdxParser.Unquoted_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.amp_quoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmp_quoted_identifier([NotNull] mdxParser.Amp_quoted_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.quoted_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuoted_identifier([NotNull] mdxParser.Quoted_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="mdxParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] mdxParser.KeywordContext context);
}
